import MainNav from "@/components/main-nav";
import MainHeader from "@/components/main-header";
import { Raleway,Montserrat } from "next/font/google";
import type { Metadata, Viewport } from "next";


import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
  minimumScale: 1,
};

export const raleway = Raleway({
  weight: ["100"],
  style: ["normal"],
  subsets: ["latin"],
});

export const montserrat = Montserrat({
  weight: ['200','400','600','800'],
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MainHeader />
        {children}
        <MainNav />
      </body>
    </html>
  );
}
